//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Assets.Code.Interfaces
{
	public interface InterfacesStados
	{
		void OnStateLevelLoad(int level);
		void StateUpdate();
		void ShowIt();
	}
}

