//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Assets.Code.Interfaces;

namespace Assets.Code.Interfaces
{
	public interface InterfacesModuleState : InterfacesStados
	{
		void EscribirEnModulo (string mensaje);
	}
}

